# .github/workflows/snake.yml - Corrected and Final Version
# .github/workflows/snake.yml - ADD THIS PERMISSIONS BLOCK

name: Generate Contribution Snake

on:
# ... (existing on: block)
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

# ⚠️ ADD THIS NEW BLOCK HERE ⚠️
permissions:
  contents: write # This grants the token permission to push to the 'output' branch

jobs:
  build:
# ... (rest of the file remains the same)
name: Generate Contribution Snake

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@master
        id: snake-svg
        with:
          github_user_name: rushour21
          # ⚠️ FIX 1: Changed 'outputs' to 'svg_out_path'
          svg_out_path: dist/github-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          # ⚠️ FIX 2: Ensure build_dir points to the folder containing the SVG
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
